# Generated by Django 4.1.5 on 2023-02-26 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('hr', 'hr'), ('employee', 'employee'), ('unknown', 'unknown')], default='unknown', max_length=8),
        ),
    ]
